name: Building GSI..

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://downloads.sourceforge.net/project/ancientrom/Tissot/AncientOS-CIVILIZATION-v4.0.1-Final-tissot-PRIMEVAL-20201211-1020-Vanilla.zip?r=https%3A%2F%2Fwww.pling.com%2Fdl%3Ffile_id%3D1607930663%26file_type%3Dapplication%2Foctet-stream%26file_name%3Ddownload-20201214072312%26file_size%3D254%26has_torrent%3D0%26project_id%3D1424176%26link_type%3Ddownload%26is_external%3Dtrue%26external_link%3Dhttps%253A%252F%252Fsourceforge.net%252Fprojects%252Fancientrom%252Ffiles%252FTissot%252FAncientOS-CIVILIZATION-v4.0.1-Final-tissot-PRIMEVAL-20201211-1020-Vanilla.zip%252Fdownload&ts=1608301754&use_mirror=deac-riga 
  ROM_NAME: Generic
  TZ: Asia/Kolkata
  MIR: wet
  ZIP_NAME: Ancientos-4.0.1
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erkanergen7/ErfanGSIs-VelanGSIs.git  ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip Aonly and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z          
       - name: Zip AB and upload 
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z      
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
         
            
